config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'sessions#home'
    
  resources :companies, only: [:index, :new, :create, :show]
   
  
  resources :ports do 
    resources :missions, only: [:index, :show]
  end  

  resources :missions 

  patch '/missions/:id', to: 'mission#update'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/session', to: 'sessions#destroy'
  get '/signup', to: 'companies#new'
  post '/signup', to: 'companies#create'

  get '/auth/github/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/company.rb
class Company < ApplicationRecord
    has_many :missions
    has_many :ports, through: :missions
    validates :name, :password, presence: true
    validates :name, uniqueness: true
    has_secure_password


    def self.find_or_create_by_omniauth(user_info)
        self.where(:name => user_info['info']['nickname']).first_or_create do |company|
         company.password = SecureRandom.hex 
        end
    end 
end

app/models/dock.rb
class Dock < ApplicationRecord
    has_many :missions
    has_many :companies, through: :missions
end

app/models/mission.rb
class Mission < ApplicationRecord
    belongs_to :port, optional: true
    belongs_to :company, optional: true
    validates :ship, presence: {message: "Need shipment info."}
    validates :ship, length: {maximum: 25, too_long: "Characters maximum is 25"}
    validates :ship, length: {minimum: 2 }    
    scope :complete, -> {where(complete: true)}
 
end

app/models/port.rb
class Port < ApplicationRecord
    has_many :missions, dependent: :destroy
    has_many :companies, through: :missions
    validates :title, :item, presence: true
    validates :title, length: {minimum: 2}
    validates :item, length: {minimum: 2}
    validates_associated :missions
    accepts_nested_attributes_for :missions

    def self.search(term)
        if term
            port = Port.find_by(:title => term)
            if port
                self.where(:id => port)
            else 
                @ports = Port.all
            end 
        else
            @ports = Port.all 
        end 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, only: [:edit, :update, :destroy] 
  before_action :authorized, only: [:edit]
  helper_method :current_user, :logged_in?
  
  def current_user
    @company ||= Company.find_by_id(session[:company_id])
  end

  def logged_in?
    !current_user.nil?
  end 

  def authorized 
    redirect_to root_path unless logged_in?
  end

  def require_login
    unless logged_in?
       flash[:error] = "You must be logged in to access this section"
      redirect_to root_path
    end 
  end 

  def authorized_editor 
    unless logged_in? && current_user == Mission.find(params[:id]).company
       flash[:error] = "You are not authorized to edit this mission!"
       redirect_to ports_path
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
     skip_before_action :authorized, only: [:new, :create]
     
    def new
        flash.keep(:notice)
        @company = Company.new 
    end 

    def index
        @companies = Company.all
    end 

    def create
        @company = Company.new(c_params)
        if @company.valid?
            @company.save
            session[:company_id] = @company.id
            redirect_to new_port_path
        else
            render new_company_path
        end
    end 

    def show
        @company = Company.find(params[:id])
    end 

    private 
    def c_params
        params.require(:company).permit(:name, :password)
    end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
    before_action :authorized_editor, only: [:edit]
    before_action :misson
    def new
        @mission = Mission.new
    end 

    def index 
        @port = Port.find_by(:id => params[:port_id])
        @missions = @port.missions
    end 

    def create
        @port = Port.find_by(:id => params[:port_id])
        @mission = @port.missions.create(m_params)
        redirect_to port_path(@port)
    end 

    def edit  
    end 

    def update
         @mission.update(m_params)
        if @mission.save
            redirect_to port_mission_path(@mission.port)
        else
            render 'edit'
        end 
    end 

    def show
    end

    def destroy
       @mission.destroy
        redirect_to ports_path
    end 

    private

    def m_params
        params.require(:mission).permit(:company_id, :port_id, :ship, :complete)
    end
    
    def misson
        @mission = Mission.find_by(:id => params[:id])
    end 
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
    before_action :require_login
    before_action :port
    
    def new
        @port = Port.new
        @port.missions.build
    end 

    def index
         @ports = Port.search(params[:term])
    end 

    def create
        @port = Port.new(p_params)
        if @port.valid?
            @port.save
            @port.missions.each do |mission|
                mission.company_id = session[:company_id]
                mission.save
            end 
              redirect_to port_path(@port)
        else 
            render new_port_path
        end 
    end 

    def edit
    end 

    def update
        @port.update(p_params)
        if @port.save
            redirect_to port_path
        else
            render 'edit'
        end 
    end 
        

    def show
    end 

    def destroy
        @port.destroy
        redirect_to ports_path
    end

    private

    def p_params
         params.require(:port).permit(:title, :item, missions_attributes: [:id, :ship, :complete])
    end 

    def port
        @port = Port.find_by(:id => params[:id])
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
     skip_before_action :authorized, only: [:new, :create, :home]
     skip_before_action :require_login, only: [:new, :create]
    
    def home
    end

    def new
    end 
        
    def create   
        if user_info = request.env['omniauth.auth']
            @company = Company.find_or_create_by_omniauth(user_info)
            session[:company_id] = @company.id
            redirect_to ports_path
        else 
            @company = Company.find_by(name: params["/signin"][:name])     
            if @company && @company.authenticate(params["/signin"][:password])  
                session[:company_id] = @company.id
                redirect_to ports_path  
            else 
                flash[:error] = "You are not a member, please sign up!"
                redirect_to signup_path
            end
        end  
    end 

    def destroy
        if current_user
            session.destroy
            flash[:notice] = "You have successfully logged out"
            redirect_to root_path
        end 
     end 

     private

     def user_info
        request.env['omniauth.auth']['provider']['info']
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<h1>Companies Index</h1>
<ol>
<% @companies.each do |c| %>
    <li>
    <p>Name: <%=c.name%></p>
    <%=link_to "To Ports", ports_path%>
    </li>
<% end %>
</ol>

app/views/companies/new.html.erb
<h1>New Company "Signup Path"</h1>
 
<%= form_for @company do |f|%>
    <% if @company.errors.any? %>
        <div id="error_explanation">
        <h2>Error:</h2>
        <ul>
            <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <%=f.label :name%>
    <%=f.text_field :name%><br><br>
    
    <%=f.label :password, 'Password'%>
    <%=f.password_field :password%><br><br>

    <%= f.submit "Welcome"%>
<%end%>

app/views/companies/show.html.erb
<h1>Show Company</h1>
<h4><%=@company.name%></h4>

app/views/docks/index.html.erb
<h1>Ports Index</h1>

<%=link_to "New Mission", new_mission_path%><br>
<ol>
<% @docks.each do |d| %>
    <li>
    <p>Port Name: <%=d.title%></p>
    <p>Item: <%=d.item%></p>
    </li>
<% end %>
</ol>

<%= button_to "Sign Out", session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNewRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css'>
  </head>
   
  <body>
  
    <% if flash[:notice] -%>
      <p class="notice"><%= flash[:notice] %></p>
    <% end -%>
    <% if flash[:error] -%>
      <p class="error"><%= flash[:error] %></p>
    <% end -%>

    <% if session[:current_user_id]%>
      <nav>
        You are logged in as: <%= @current_user.name%>
      </nav>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/missions/_form.html.erb
<h3>Hello <%=@company.name%></h3>

<%= form_for @mission do |f| %>

    <% if @mission.errors.any? %>
        <div id="error_explanation">
        <h2>Error:</h2>
        <ul>
            <% @mission.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <%= f.hidden_field :company_id, value: session[:company_id] %>

    <%= f.hidden_field :port_id %>

    <%=f.label :ship, "Brief Mission Info"%><br>
    <%=f.text_field :ship%><br>
    
    <%=f.submit%>
<%end%>

app/views/missions/edit.html.erb
<h1>Mission Edit</h1>
<%= render partial: 'form', locals: {topic: @mission} %>

app/views/missions/index.html.erb
<h1>Mission Index</h1>

<h4><% if logged_in? %>Welcome, <%= current_user.name %><% end %></h4>

<%=link_to "New Port", new_port_path%><br>

<%= button_to "Sign Out", session_path, method: :delete %>

<ol>
<% @missions.each do |m| %>
    <li>
    <h5>Company: <%=m.company.name%></h5>
    <h5>Port: <%=m.port.title%></h5>
    <h5>Shipment Info: <%=m.ship%></h5>
    <h5>Complete <%= m.complete %></h5>
    <%=link_to "Back", port_path(m.port, m)%><br>
    <%=link_to "Mission Show", port_mission_path(m.port, m)%>
    
    </li>
<% end %>
</ol>

app/views/missions/new.html.erb
<h1>Welcome to New Missions</h1>
<%= render partial: 'form', locals: {topic: @mission} %>

app/views/missions/show.html.erb
<h1>Mission Show</h1>

<ol>
<li>
<h3>Company: <%=@mission.company.name%></h3>
<h3>Port: <%=@mission.port.title%></h3>
<h3>Port Item: <%=@mission.port.item%></h3>
<h3>Mission Info: <%=@mission.ship%></h3>
<h3>Complete: <%=@mission.complete%> </h3>
</li>
</ol>

<%= link_to "Edit Mission Info", edit_mission_path(@mission)%><br>
<%= link_to 'Delete', mission_path(@mission), method: :delete %><br>
<%= link_to "Back", port_path(@mission.port)%>
<%= button_to "Sign Out", session_path, method: :delete %>

app/views/ports/_form.html.erb
<h3>Hello <%=@company.name%></h3>

<%= form_for @port do |f| %>
    
    <% if @port.errors.any? %>
        <div id="error_explanation">
        <h2>Error:</h2>
        <ul>
            <% @port.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <%= f.hidden_field :port_id, value: session[:port_id] %>

    <%=f.label :title, "Name of Port"%>
    <%=f.text_field :title%><br>
    
    <%=f.label :item, "Item"%>
    <%=f.text_field :item%><br>
    
    <h3>Missions</h3>
    <%= f.fields_for :missions, @port.missions do |mf|%>
        <%=mf.label :ship, "Brief Mission Info"%><br>
        <%=mf.text_field :ship%><br>
         <%= mf.label :complete, "Complete?"%>
        <%= mf.check_box :complete %><br>
    <% end %>

    <%=f.submit "Create"%>
<%end%>

app/views/ports/edit.html.erb
<h2>Welcome to Ports Edit</h2>
<%= render partial: 'form', locals: {topic: @port} %>

app/views/ports/index.html.erb
<h1>Ports Index</h1>

<h4><% if logged_in? %>Welcome, <%= current_user.name %><% end %></h4>

<%= form_tag("/ports", method: 'get') do %>
    Search Port Title: <%= text_field_tag :term %>
    <%= submit_tag "Search" %>
<% end %> 

<%=link_to "New Port", new_port_path%><br>

<%= button_to "Sign Out", session_path, method: :delete %>

<ol>
<% @ports.each do |p| %>
    <li>
    <% p.companies.each do |pc|%>
        <h5>Company: <%=pc.name%></h5>
    <% end %>
    <h5>Port Name: <%=p.title%></h5>
    <h5>Item: <%=p.item%></h5>
    <%=link_to "Port Details", port_path(p)%><br><br>
    
    </li>
<% end %>
</ol>

app/views/ports/new.html.erb
<h1>Welcome to New Ports</h1>

<%= render partial: 'form', locals: {topic: @mission} %>

app/views/ports/show.html.erb
<h1>Welcome to Ports Show</h1>
<%= button_to "Sign Out", session_path, method: :delete %>

<ol>
    <li>
    <% @port.companies.each do |company| %>
        <h3>Company Name: <%=company.name%></h3>
    <% end %>    
    
    <h3>Port Title: <%=@port.title%></h3>
    <h3>Port Items: <%=@port.item%></h3>

    <h3>Completed Missions:</h3>
    <%= link_to "Mission View", port_missions_path(@port)%>
    <ul>
    <% @port.missions.complete.each do |miss| %>
        <li>
            <h4>Brief Mission Info: <%= miss.ship %></h4>
            <h4>Complete: <%= miss.complete%></h4>
        </li>
        <% end %>
    
    </ul><br>

    <%= link_to "Edit Port", edit_port_path(@port)%><br><br>
    <%= link_to 'Delete', port_path(@port), method: :delete %><br><br>
    <%= link_to "Port Index", ports_path%><br><br>
    
    </li>
</ol>